# Generated by Django 3.1.2 on 2020-10-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='num',
        ),
    ]
