# Generated by Django 3.1.2 on 2020-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20201016_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='num',
            field=models.CharField(max_length=30),
        ),
    ]
